#!/bin/bash

VERSION="1.0.0-openziti-p-petrov-release"
REVISION="petar-custom"
DATE=$(date +"%Y-%m-%d %H:%M:%S")

cat > common/version/info_generated.go <<EOF
// Code generated by Petar's custom build system. DO NOT EDIT.

package version

var (
        Version   = "$VERSION"
        Revision  = "$REVISION"
        BuildDate = "$DATE"
)
EOF

echo "Generated version file:"
cat common/version/info_generated.go

echo "Building ziti-petar..."
go build -o ziti-petar ./ziti

echo "Build complete."

