// Code generated by Petar's custom build system. DO NOT EDIT.

package version

var (
        Version   = "1.0.0-openziti-p-petrov-release"
        Revision  = "petar-custom"
        BuildDate = "2026-01-02 14:31:48"
)
